config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'questions#index'

  resources :questions do
    resources :answers, shallow: true do
      member do
        patch :best
      end
    end
  end
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
  validates :body, presence: true
  default_scope { order(best: :desc) }

  def set_best
    Answer.where(question_id: self.question_id).update(best: false)
    update(best: true)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  belongs_to :user
  validates :title, :body, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions
  has_many :answers

  def author_of?(resource)
    id == resource.user_id
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_question, only: %i[create]
  before_action :load_answer, only: %i[show destroy update best]

  def create
    @answer = @question.answers.create(answer_params.merge(user_id: current_user.id))
  end

  def update
    @answer = Answer.find(params[:id])
    @answer.update(answer_params)
    @question = @answer.question
  end

  def destroy
    if current_user.author_of?(@answer)
      @answer.destroy
      @alert = 'You are not the author of this answer.'

    else
      @alert = 'You are not the author of this answer.'
    end
  end

  def best
    @question = @answer.question
    @answer.set_best if current_user.author_of?(@question)
  end

  private

  def load_question
    @question = Question.find(params[:question_id])
  end

  def load_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :load_question, only: %i[show edit update destroy]

  def index
    @questions = Question.all
  end

  def show
    @answer = @question.answers.new
  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.create(question_params)

    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      @question
    end
  end

  def destroy
    if current_user.author_of?(@question)
      @question.destroy
      redirect_to questions_path, notice: 'Your question succesfully deleted.'
    else
      redirect_to @question, alert: 'You are not the author of this question.'
    end
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
end

app/views/answers/_answer.html.slim
div class="answer_#{answer.id}"
  p = answer.body
  - if current_user&.author_of?(answer)
    .btn-toolbar
      = link_to 'Edit', '#', class: 'edit-answer-link btn btn-primary btn-sm', data: {answer_id: answer.id}
      = link_to 'Delete', answer_path(answer), class: 'btn btn-primary btn-sm', method: :delete, remote: true

      - if current_user&.author_of?(answer.question) && !answer.best
          = link_to best_answer_path(answer), class: 'best btn btn-primary btn-sm', method: :patch, remote: true
            span.glyphicon.glyphicon-chevron-up

    div class="error_answer_#{answer.id}"

    = form_with model: answer, class: 'hidden', html: {id: "edit-answer-#{answer.id}"} do |f|
      .form-group
        = f.label :body, 'Your answer'
        = f.text_area :body, :class => 'form-control'
      .form-group
        = f.submit 'Save Answer'

app/views/answers/best.js.erb
$('.answers').html('<%= j render @question.answers %>');

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
$('.answers').append('<%= j render @answer %>');
$('.new-answer #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
var answerId = <%= @answer.id %>;

$('.error_answer_' + answerId).html('<%= render 'shared/errors', resource: @answer %>');

<% if !@answer.errors.present? %>
  $('.answer_' + answerId).remove();
<% end %>

app/views/answers/update.js.erb
var answerId = <%= @answer.id %>;

$('.error_answer_' + answerId).html('<%= render 'shared/errors', resource: @answer %>');

<% if !@answer.errors.present? %>
$('.answers').html('<%= j render @question.answers %>');
<% end %>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset='utf-8'
    = csrf_meta_tags
    = stylesheet_link_tag 'application', :media => 'all'
    = javascript_include_tag 'application'
  body
    = render partial: 'shared/nav'

    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
        .col-lg-3
          .well.sidebar-nav
            h3 Sidebar
            ul.nav.nav-list
              li.nav-header Sidebar
              li = link_to "Link 1", "/path1"
              li = link_to "Link 2", "/path2"
              li = link_to "Link 3", "/path3"

app/views/questions/_question.html.slim
.error_question
h1 = @question.title
.content = @question.body
- if current_user&.author_of?(@question)

  = form_with model: @question, class: 'hidden' do |f|
    .form-group
      = f.label :title
      = f.text_field :title, :class => 'form-control'
    .form-group
      = f.label :body
      = f.text_area :body, :class => 'form-control'
    .form-group
      = f.submit 'Edit', :class => 'btn btn-primary'

  .btn-toolbar
    = link_to 'Edit', '#', class: 'edit-question-link  btn btn-primary btn-sm'
    = link_to 'Delete', question_path(@question), class: 'btn btn-primary btn-sm', method: :delete, data: { confirm: 'Вы уверены?' }

app/views/questions/index.html.slim
p = link_to 'Ask question', new_question_path

- @questions.each do |question|
  = link_to question.title, question_path(question)

app/views/questions/new.html.slim
= render 'shared/errors', resource: @question

h1 Create question
= form_with model: @question, local: true do |f|
  .form-group
    = f.label :title
    = f.text_field :title, :class => 'form-control'
  .form-group
    = f.label :body
    = f.text_area :body, :class => 'form-control'
  .form-group
    = f.submit 'Ask', :class => 'btn btn-primary'

app/views/questions/show.html.slim
.question
  = render @question
hr

h2 = 'Answers list'

.answers
  = render @question.answers

hr

.answer-errors
  = render 'shared/errors', resource: @answer

= form_with model: [@question, @answer], class: 'new-answer' do |f|
  .form-group
    = f.label :body
    = f.text_area :body, :class => 'form-control'
  .form-group
    = f.submit 'Create Answer', :class => 'btn btn-primary'

app/views/questions/update.js.erb
$('.error_question').html('<%= render 'shared/errors', resource: @question %>');

<% if !@question.errors.present? %>
  $('.question h1').html('<%= @question.title %>');
  $('.question .content').html('<%= @question.body %>');
<% end %>

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_nav.html.slim
.navbar.navbar-default.navbar-static-top
  .container
    button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse"
      span.icon-bar
      span.icon-bar
      span.icon-bar
    a.navbar-brand href="#"Qna
    .navbar-collapse.collapse.navbar-responsive-collapse
      ul.nav.navbar-nav
        - if user_signed_in?
          li = link_to current_user.email
          li = link_to 'Log out', destroy_user_session_path, method: :delete
        - else
          li = link_to 'Sign in', new_user_session_path
          li = link_to 'Registration', new_user_registration_path